//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("977, 836")]
        public global::System.Drawing.Size CheckInForm_Size {
            get {
                return ((global::System.Drawing.Size)(this["CheckInForm_Size"]));
            }
            set {
                this["CheckInForm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CheckInForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["CheckInForm_Location"]));
            }
            set {
                this["CheckInForm_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("917")]
        public int CheckInForm_addedList_ColumnHeaderWidth {
            get {
                return ((int)(this["CheckInForm_addedList_ColumnHeaderWidth"]));
            }
            set {
                this["CheckInForm_addedList_ColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("917")]
        public int CheckInForm_modifiedList_ColumnHeaderWidth {
            get {
                return ((int)(this["CheckInForm_modifiedList_ColumnHeaderWidth"]));
            }
            set {
                this["CheckInForm_modifiedList_ColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("917")]
        public int CheckInForm_deletedList_ColumnHeaderWidth {
            get {
                return ((int)(this["CheckInForm_deletedList_ColumnHeaderWidth"]));
            }
            set {
                this["CheckInForm_deletedList_ColumnHeaderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState CheckInForm_State {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["CheckInForm_State"]));
            }
            set {
                this["CheckInForm_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169")]
        public int CheckInForm_topSplitPanel_SplitterDistance {
            get {
                return ((int)(this["CheckInForm_topSplitPanel_SplitterDistance"]));
            }
            set {
                this["CheckInForm_topSplitPanel_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235")]
        public int CheckInForm_bottomSplitPanel_SplitterDistance {
            get {
                return ((int)(this["CheckInForm_bottomSplitPanel_SplitterDistance"]));
            }
            set {
                this["CheckInForm_bottomSplitPanel_SplitterDistance"] = value;
            }
        }
    }
}
